library(tidyverse)

#Jia Jinbu. 2020.09.15
#Usage: Rscript cal_polya_transcript_ir.R read.intron.pos.splicing.txt \
#						read.info.txt read.rna_unspliced_ratio.stat read.intron_unspliced_ratio.stat
#
# read.intron.pos.splicing.txt is generated by `prepare_data_for_splice_kinetics.py`
# read.info.txt is generated by `merge_read_info.R`
# output:
# read.rna_unspliced_ratio.stat
# read.intron_unspliced_ratio.stat

args <- commandArgs(T)
file_rel_pos = args[1]
file_read_info = args[2]
fileout_rna_stat = args[3]
fileout_intron_stat = args[4]

rel_pos <- read_tsv(file_rel_pos)
read_info <- read_tsv(file_read_info, na="NA")

select_read_info <- filter(read_info, type == "polya")
select_rel_pos <- filter(rel_pos, read_core_id %in% select_read_info$read_core_id)

rna_stat <- select_read_info %>%
				group_by(mRNA) %>%
				summarise(total_read_num=n(), 
				          ir_read_num = sum(retention_introns != ""),
				          ir_ratio = ir_read_num/total_read_num)

ir_stat <- select_rel_pos %>% 
				group_by(intron_id) %>% 
				summarise(total_read_num=n(), 
						  ir_read_num=sum(retention), 
						  ir_ratio=ir_read_num/total_read_num)

write_tsv(rna_stat, fileout_rna_stat)
write_tsv(ir_stat, fileout_intron_stat)



